### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-toml#6]
gettingStarted.adoc and introduction.adoc are still TODO

**Comment by yawkat** [comment]
added some basic docs in b4a3c62239729ec8d189026b83df033ba0515081

**Comment by sdelamo** [comment]
Every repository contains a repository.adoc entry linking to the repo:

https://github.com/micronaut-projects/micronaut-security/blob/master/src/main/docs/guide/repository.adoc

and a releaseHistory

https://github.com/micronaut-projects/micronaut-security/blob/master/src/main/docs/guide/releaseHistory.adoc

and toc.yml is:

```yaml
introduction:
  title: Introduction
releaseHistory: Release History
....
....
....
....
repository: Repository
```
