### ISSUE TITLE
[BUG] failed to parse integer in inline table

### ISSUE THREAD

**Issue by wbprime** [micronaut-projects/micronaut-toml#93]
In micronaut-toml 1.1.1, it failed to parse integer value in inline tables by throwing out NumberFormatExcetption.

e.g., failed to parse:

```toml
[gateway.transport-manager.pools]
default = { thread-count = 1, queue-length = 678 }
fix = { thread-count = 1, queue-length = 100 }
apex = { thread-count = 1, queue-length = 100 }
```

but ok to parse:

```toml
[gateway.transport-manager.pools.default]
thread-count = 1
queue-length = 678

[gateway.transport-manager.pools.fix]
thread-count = 1
queue-length = 100

[gateway.transport-manager.pools.apex]
thread-count = 1
queue-length = 100
```
